### PR TITLE
Enable multiple deployment

### PR DESCRIPTION
**Pull request by abbedsedk**

### CODE REVIEW

**Comment by lamw** [comment]
This PR looks to only contain README change? Looks like you may have forgotten to include the rest of the changes ... Also good to squash the other commits

**Comment by abbedsedk** [comment]
Thank you for your patience, I committed the 2 files [98a9915] and [dadbe3b]. That should be good ... let me know if there is anything else.

And for initial merge conflict, i think it happened because from the forked repository under Contribute i clicked pull request from there, i learned that was not the right way,
in the [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) it show that PR from forked repository is made **in** the upstream repository.

**Comment by abbedsedk** [comment]
Since it's already merged in #6 i think we could close this

**Comment by abbedsedk** [comment]
The following PR will supperseed this one, so i close it

**Pull request closed without merging**
